baseURL = "https://khatnaps.net/"
languageCode = "en-us"
title = "K.T.H."
theme = "smol"
copyright = "Kha Huynh"
paginate = 4

# Parameters
[params]
    subtitle = "Read a girl who dates books? ☃️"
    dateFmt = "01-02-2006"
    favicon = "/static/favicon.ico"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2

  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 3

  [[menu.main]]
        identifier = "reading-list"
        name = "Reading list"
        url = "/reading-list/"
        weight = 4

  [[menu.main]]
        identifier = "goodies"
        name = "◐"
        url = "/goodies/"
        weight = 5
